databases:
  - name: chatgpt-dashboard-db
    databaseName: chatgpt_dashboard
    user: chatgpt_dashboard_user
    plan: free

services:
  # Backend API Service
  - type: web
    name: chatgpt-dashboard-backend
    runtime: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: chatgpt-dashboard-db
          property: connectionString
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: OPENAI_API_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_API_CREDENTIALS
        sync: false

  # Frontend React App
  - type: web
    name: chatgpt-dashboard-frontend
    runtime: static
    buildCommand: cd frontend && npm install && REACT_APP_API_URL=https://chatgpt-dashboard-backend.onrender.com/api npm run build
    staticPublishPath: ./frontend/build
    headers:
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
    routes:
      - type: rewrite
        source: /*
        destination: /index.html