#!/bin/bash

echo "🔧 Render CLI Commands to Fix Custom Domain"
echo "========================================="
echo ""
echo "1. First, authenticate (if not already done):"
echo "   render login"
echo ""
echo "2. List all services to find IDs:"
echo "   render services list"
echo ""
echo "3. Look for these services:"
echo "   - calendar-backend or any service with 'Personal Dashboard'"
echo "   - chatgpt-dashboard-frontend"
echo ""
echo "4. Remove domain from wrong service:"
echo "   # Replace SERVICE_ID with the calendar-backend service ID"
echo "   render custom-domains remove dashboard.davidcfacfp.com --service-id SERVICE_ID"
echo ""
echo "5. Add domain to correct service:"
echo "   # Replace SERVICE_ID with chatgpt-dashboard-frontend service ID"
echo "   render custom-domains add dashboard.davidcfacfp.com --service-id SERVICE_ID"
echo ""
echo "6. Verify the change:"
echo "   ./verify-domain-update.sh"