#!/bin/bash

echo "🚀 ChatGPT-Google Dashboard Deployment Guide"
echo "==========================================="
echo ""
echo "Follow these steps to deploy to Render:"
echo ""
echo "1. PREPARE YOUR CREDENTIALS"
echo "   -------------------------"
echo "   You'll need:"
echo "   ✓ OpenAI API Key (from https://platform.openai.com/api-keys)"
echo "   ✓ Google Cloud credentials (optional for now)"
echo "   ✓ GitHub account with your repo"
echo "   ✓ Render account (free at https://render.com)"
echo ""
echo "2. DEPLOY WITH RENDER BLUEPRINT (Easiest Method)"
echo "   ---------------------------------------------"
echo "   a) Go to https://dashboard.render.com/blueprints"
echo "   b) Click 'New Blueprint Instance'"
echo "   c) Connect your GitHub account if not already connected"
echo "   d) Select 'dvanosdol88/ChatGPT-Google-Dashboard' repository"
echo "   e) Render will detect the render.yaml file automatically"
echo "   f) You'll see 3 resources to create:"
echo "      - PostgreSQL Database (chatgpt-dashboard-db)"
echo "      - Backend Web Service (chatgpt-dashboard-backend)"
echo "      - Frontend Static Site (chatgpt-dashboard-frontend)"
echo ""
echo "3. CONFIGURE ENVIRONMENT VARIABLES"
echo "   --------------------------------"
echo "   When prompted, add these environment variables:"
echo "   • OPENAI_API_KEY = [Your OpenAI API key]"
echo "   • GOOGLE_CLIENT_ID = [Optional - leave empty for now]"
echo "   • GOOGLE_CLIENT_SECRET = [Optional - leave empty for now]"
echo "   • GOOGLE_API_CREDENTIALS = [Optional - leave empty for now]"
echo ""
echo "4. DEPLOY"
echo "   -------"
echo "   Click 'Apply' to start deployment"
echo "   This will take 5-10 minutes for the first deployment"
echo ""
echo "5. UPDATE FRONTEND API URL"
echo "   ------------------------"
echo "   After deployment, you'll get URLs like:"
echo "   • Backend: https://chatgpt-dashboard-backend-xxx.onrender.com"
echo "   • Frontend: https://chatgpt-dashboard-frontend-xxx.onrender.com"
echo ""
echo "   Update the frontend to use your backend URL:"
echo "   - Go to your frontend service in Render"
echo "   - Add environment variable:"
echo "     REACT_APP_API_URL = https://chatgpt-dashboard-backend-xxx.onrender.com/api"
echo "   - Redeploy the frontend"
echo ""
echo "6. VERIFY DEPLOYMENT"
echo "   -----------------"
echo "   • Check backend health: https://[your-backend].onrender.com/api/health"
echo "   • Access frontend: https://[your-frontend].onrender.com"
echo ""
echo "Press Enter to open Render Dashboard in your browser..."
read -p ""

# Try to open Render dashboard
if command -v xdg-open &> /dev/null; then
    xdg-open "https://dashboard.render.com/blueprints"
elif command -v open &> /dev/null; then
    open "https://dashboard.render.com/blueprints"
elif command -v start &> /dev/null; then
    start "https://dashboard.render.com/blueprints"
else
    echo "Please open https://dashboard.render.com/blueprints in your browser"
fi