#!/bin/bash

echo "🚀 Simple Render Deployment"
echo "=========================="
echo ""
echo "Since automated deployment is complex, here's the fastest way:"
echo ""
echo "1. Open Render Dashboard:"
echo "   https://dashboard.render.com/select-repo"
echo ""
echo "2. Click 'Connect account' if needed"
echo ""
echo "3. Select your repository:"
echo "   dvanosdol88/ChatGPT-Google-Dashboard"
echo ""
echo "4. Create these services:"
echo ""
echo "   A) PostgreSQL Database"
echo "      - Click 'New' → 'PostgreSQL'"
echo "      - Name: chatgpt-dashboard-db"
echo "      - Database: chatgpt_dashboard"
echo "      - User: chatgpt_dashboard_user"
echo "      - Region: Oregon (US West)"
echo "      - Plan: Free"
echo ""
echo "   B) Backend Service"
echo "      - Click 'New' → 'Web Service'"
echo "      - Connect same repo"
echo "      - Name: chatgpt-dashboard-backend"
echo "      - Root Directory: backend"
echo "      - Runtime: Node"
echo "      - Build Command: npm install"
echo "      - Start Command: npm start"
echo "      - Environment Variables:"
echo "        DATABASE_URL = (copy from PostgreSQL dashboard)"
echo "        OPENAI_API_KEY = $1"
echo "        PORT = 5000"
echo ""
echo "   C) Frontend Service"
echo "      - Click 'New' → 'Static Site'"
echo "      - Connect same repo"
echo "      - Name: chatgpt-dashboard-frontend"
echo "      - Root Directory: frontend"
echo "      - Build Command: npm install && npm run build"
echo "      - Publish Directory: build"
echo "      - After deploy, add environment variable:"
echo "        REACT_APP_API_URL = https://[your-backend].onrender.com/api"
echo ""
echo "Total time: ~10 minutes"
echo ""
echo "Opening Render Dashboard..."
echo ""

# Try to open browser
if command -v xdg-open &> /dev/null; then
    xdg-open "https://dashboard.render.com/new/database"
elif command -v open &> /dev/null; then
    open "https://dashboard.render.com/new/database"
elif command -v cmd.exe &> /dev/null; then
    cmd.exe /c start "https://dashboard.render.com/new/database"
else
    echo "Please open: https://dashboard.render.com/new/database"
fi