#!/bin/bash

echo "🚀 Quick Deploy to Render"
echo "======================="
echo ""
echo "This will open Render with pre-configured URLs for easy deployment."
echo ""
echo "Step 1: Create Database First"
echo "-----------------------------"
echo "Opening database creation page..."
echo "https://dashboard.render.com/new/database"
echo ""
echo "Use these settings:"
echo "  Name: chatgpt-dashboard-db"
echo "  Database: chatgpt_dashboard"
echo "  User: chatgpt_dashboard_user"
echo "  Region: Oregon"
echo "  Plan: Free"
echo ""
echo "Press Enter after creating the database..."
read -p ""

echo ""
echo "Step 2: Create Backend Service"
echo "-----------------------------"
echo "Opening backend service creation..."
echo "https://dashboard.render.com/new/web-service?repo=https://github.com/dvanosdol88/ChatGPT-Google-Dashboard"
echo ""
echo "Use these settings:"
echo "  Name: chatgpt-dashboard-backend"
echo "  Root Directory: backend"
echo "  Build Command: npm install"
echo "  Start Command: npm start"
echo "  Environment Variables:"
echo "    DATABASE_URL = (copy from your new database)"
echo "    OPENAI_API_KEY = rnd_IwCrq0zq4qCyGc4fP6hLBQgd5nLW"
echo "    PORT = 5000"
echo ""
echo "Press Enter after creating the backend..."
read -p ""

echo ""
echo "Step 3: Create Frontend Service"
echo "------------------------------"
echo "Opening frontend service creation..."
echo "https://dashboard.render.com/new/static-site?repo=https://github.com/dvanosdol88/ChatGPT-Google-Dashboard"
echo ""
echo "Use these settings:"
echo "  Name: chatgpt-dashboard-frontend"
echo "  Root Directory: frontend"
echo "  Build Command: npm install && npm run build"
echo "  Publish Directory: build"
echo ""
echo "After it deploys, add this environment variable:"
echo "  REACT_APP_API_URL = https://[your-backend].onrender.com/api"
echo ""
echo "🎉 That's it! Your services will build and deploy in ~10 minutes."